In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle


img_width, img_height = 640, 480

# training path
DATADIR = "/Users/crisramos/Desktop/Deep Learning/Project FArmerINsurance/imgs/train"
categories= [ 'c0','c1','c2','c3','c4','c5','c6','c7','c8','c9']

for category in categories:
    path  = os.path.join(DATADIR, category)
    for img in os.listdir(path):
        img_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
        plt.imshow(img_array,cmap="gray")
        plt.show()
        break
    break



#307200 size of pics




/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<Figure size 640x480 with 1 Axes>

In [2]:
print(img_array)
#IMG_SIZE = 480*640 

[[68 67 67 ... 45 56 91]
 [70 69 69 ... 76 73 69]
 [72 71 71 ... 86 78 74]
 ...
 [ 5  5  5 ... 15 15 14]
 [ 5  5  5 ... 14 15 16]
 [ 5  5  5 ... 13 15 17]]


In [3]:
training_data = []
def create_td():
    for category in categories:
        path  = os.path.join(DATADIR, category)
        class_num = categories.index(category)
        i=0
        for img in os.listdir(path):
            img_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
            training_data.append([img_array,class_num])
            i+=1
            if i >1300:
                break

        
        
        
        

In [4]:
create_td()
print(len(training_data))

13010


In [5]:
import random
random.shuffle(training_data)
for sample in training_data[:10]:
    print(sample[1])

8
5
8
2
0
9
4
4
4
9


In [6]:
X= []
y=[]
for features, label in training_data:
    X.append(features)
    y.append(label)
    
X= np.array(X).reshape(-1, 480,640,1)  #if its color 1 has tobe 3!!! 

In [ ]:
# only for saving purposes
#**********************************************

# file too big wont save anyway.............

#**********************************************
import pickle 

#pickle_out = open("X.pickle","wb")
#pickle.dump(X, pickle_out)
#pickle_out.close()

#pickle_out = open("y.pickle","wb")
#pickle.dump(y, pickle_out)
#pickle_out.close()
#print(X[0])
#print(y[0])

In [ ]:
#pickle_in= open("X.pickle","rb")
#X = pickle.load(pickle_in)

#pickle_in= open("y.pickle","rb")
#y = pickle.load(pickle_in)

In [7]:
from keras.utils import np_utils
y = np_utils.to_categorical(y, 10)
X = X/255



Using TensorFlow backend.


In [8]:
print('ready..')

ready..


In [42]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D


model=Sequential()



In [43]:
# CNN first layer (with 32 3x3 filter):
print('input=',X.shape[1:])
model.add(   Conv2D(32,(11,11),input_shape= X.shape[1:], strides=4)  )
model.add(Activation("relu"))
print(model.output_shape)# 480 -11 +3 / 3 + 1

# pooling layer 1
model.add(MaxPooling2D(pool_size= (3,3),strides=2))
print(model.output_shape) # 118 - 3 +1 /3-1

input= (480, 640, 1)
(None, 118, 158, 32)
(None, 58, 78, 32)


In [44]:




# 2 Conv lsyer
model.add(Conv2D(32,(5,5),strides=1,padding='same'))
model.add(Activation("relu"))
print(model.output_shape)

# pooling layer 2
model.add(MaxPooling2D(pool_size= (3,3),strides=2))
print(model.output_shape)

# 3 Conv lsyer
model.add(Conv2D(32,(3,3),strides=1,padding='same'))
model.add(Activation("relu"))
print(model.output_shape)

# 4 Conv lsyer
model.add(Conv2D(32,(3,3),strides=1,padding='same'))
model.add(Activation("relu"))
print(model.output_shape)

# 5 Conv lsyer
model.add(Conv2D(32,(3,3),strides=1,padding='same'))
model.add(Activation("relu"))
print(model.output_shape)

# pooling layer 3
model.add(MaxPooling2D(pool_size= (3,3),strides=2))
print(model.output_shape)
# Dropout layer to avoid overfiiting
model.add(Dropout(0.5))



(None, 58, 78, 32)
(None, 28, 38, 32)
(None, 28, 38, 32)
(None, 28, 38, 32)
(None, 28, 38, 32)
(None, 13, 18, 32)


In [45]:

# output Fully connected Dense layers:
model.add(Flatten())
print(model.output_shape)
model.add(Dense(1028))
model.add(Activation("relu"))
print(model.output_shape)


model.add(Dropout(0.5))


model.add(Flatten())
print(model.output_shape)
model.add(Dense(1028))
model.add(Activation("relu"))
print(model.output_shape)


model.add(Dense(10))
model.add(Activation('softmax'))
print(model.output_shape)




(None, 7488)
(None, 1028)
(None, 1028)
(None, 1028)
(None, 10)


In [46]:
from keras.metrics import categorical_accuracy
model.compile(loss="categorical_crossentropy",
             optimizer="adam",
             metrics=[categorical_accuracy])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 118, 158, 32)      3904      
_________________________________________________________________
activation_37 (Activation)   (None, 118, 158, 32)      0         
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 58, 78, 32)        0         
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 58, 78, 32)        25632     
_________________________________________________________________
activation_38 (Activation)   (None, 58, 78, 32)        0         
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 28, 38, 32)        0         
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 28, 38, 32)        9248      
__________

In [47]:
from time import time
import time
name= "convNN 5conv layers 480 640".format(int(time.time()))

from tensorflow.keras.callbacks import TensorBoard
tensorboard = TensorBoard(log_dir="logs/{}".format(name), batch_size = 32, update_freq= 'batch',write_graph=True)


In [48]:
#from keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1)
fitted_model= model.fit(X,y, epochs= 6, validation_split=.1,
                        batch_size=32, verbose= 1,callbacks =[es,tensorboard])

Train on 11709 samples, validate on 1301 samples
Epoch 1/6
 1088/11709 [=>............................] - ETA: 27:46 - loss: 2.3081 - categorical_accuracy: 0.0993

KeyboardInterrupt: 

In [ ]:
import cv2
import tensorflow as tf
categories= [ 'c0','c1','c2','c3','c4','c5','c6','c7','c8','c9']



path='/Users/crisramos/Desktop/Deep Learning/Project FArmerINsurance/imgs/test'# testing path
testing_set=[]
c=0
im='img_11.jpg'
img_arr=cv2.imread(os.path.join(path,im), cv2.IMREAD_GRAYSCALE)
#img_arr =cv2.resize(img_arr,(300,300))
testing_set.append(img_arr)
#img_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_COLOR)
plt.imshow(img_arr,cmap="gray")

#plt.imshow(img_array,cmap="gray")
plt.show()
           
    
X_test= []
for d in testing_set:
    X_test.append(d)
    
    
X_test= np.array(X_test).reshape(-1, 480,640,1)  #if its color 1 has tobe 3!!! 

     
#X_test = np.array(testing_set).reshape(-1, 480,640,1)    
#print(X_test.shape)       

#X_test = X_test.reshape(len(X_test),-1)

#X_test_new = my_pca.transform(X_test)
#X_test_new= np.array(X_test).reshape(-1, 10,100,1)


prediction=model.predict(X_test)
print( "  0 1  2  3  4  5  6  7  8  9")
print(prediction)

In [ ]:
print(os.path.join(path,im))